exec_command:
  fields:
    host:
      default: 172.17.0.1
      example: 172.17.0.1
      selector:
        text:
    port:
      default: 22
      example: 22
      selector:
        number:
          min: 1
          max: 65535
    user:
      default: pi
      example: pi
      selector:
        text:
    pass:
      default: raspberry
      example: raspberry
      selector:
        text:
    command:
      example: ls -la
      required: true
      selector:
        text:
    private_key:
      example: /config/ssh/id_rsa
      selector:
        text:
